#!/bin/sh

if [ "$1" = "" ]; then
  echo "Usage: addlicense <Version>"
  echo "Eg: addlicense 1.0.0"
  exit 1
fi

# eject the mounted volume
hdiutil detach /Volumes/LAN-Messenger || true

# compress the disk image
hdiutil convert LAN-Messenger.dmg -format UDBZ -o lmc_$1_intel.dmg

# add the license to the disk image (best-effort)
python3 ./licenseDMG.py lmc_$1_intel.dmg ./package/eula/license.txt || true

# move the final image to output folder
mv -f -v lmc_$1_intel.dmg ../

# delete the intermediate files
rm -r -v LAN-Messenger.app
rm -f -v LAN-Messenger.dmg

exit 0
