#!/bin/sh

if [ "$1" = "" ]; then
  echo "Usage: x11_setup <App Version>"
  echo "eg: x11_setup 1.0.0"
  exit 1
fi

sudo echo "COPYING FILES..."
sudo cp -v /usr/lib/libQtCore.so.4 ./x11_package/usr/lib/lmc/libQtCore.so.4
sudo cp -v /usr/lib/libQtGui.so.4 ./x11_package/usr/lib/lmc/libQtGui.so.4
sudo cp -v /usr/lib/libQtNetwork.so.4 ./x11_package/usr/lib/lmc/libQtNetwork.so.4
sudo cp -v /usr/lib/libQtXml.so.4 ./x11_package/usr/lib/lmc/libQtXml.so.4
sudo cp -v ../release/libcrypto.so.1.0.0 ./x11_package/usr/lib/lmc/libcrypto.so.1.0.0
sudo cp -v ../release/liblmcapp.so.1 ./x11_package/usr/lib/lmc/liblmcapp.so.1
sudo cp -v ../release/lmc.rcc ./x11_package/usr/lib/lmc/lmc.rcc
sudo cp -v ../release/lmc ./x11_package/usr/lib/lmc/lmc
sudo cp -v ../release/COPYING ./x11_package/usr/lib/lmc/COPYING
sudo cp -v -r ../release/lang ./x11_package/usr/lib/lmc/lang
sudo cp -v -r ../release/sounds ./x11_package/usr/lib/lmc/sounds
sudo cp -v -r ../release/imageformats ./x11_package/usr/lib/lmc/imageformats

echo "BUILDING PACKAGE..."
sudo dpkg-deb -z9 -Zlzma -b x11_package lmc_$1_i386.deb

echo "DONE."
exit 0