#!/bin/sh
set -e

if [ "$1" = "" ]; then
  echo "Usage: setup <App Version>"
  echo "eg: setup 1.0.0"
  exit 1
fi

echo "COPYING FILES..."
QTDIRLIB=""
if [ "$PACKAGE_MODE" != "_min" ]; then
  # Bundle the Qt 6 libraries the app links plus the plugin sets it needs.
  QTDIRLIB=$(dirname $(find / $PWD -type f -name "*libQt6Core.so.6*" 2> /dev/null) | head -1) > /dev/null

  sudo cp -v $QTDIRLIB/libQt6Core.so.6 ./package/usr/lib/lmc/libQt6Core.so.6
  sudo cp -v $QTDIRLIB/libQt6Gui.so.6 ./package/usr/lib/lmc/libQt6Gui.so.6
  sudo cp -v $QTDIRLIB/libQt6Widgets.so.6 ./package/usr/lib/lmc/libQt6Widgets.so.6
  sudo cp -v $QTDIRLIB/libQt6Network.so.6 ./package/usr/lib/lmc/libQt6Network.so.6
  sudo cp -v $QTDIRLIB/libQt6Xml.so.6 ./package/usr/lib/lmc/libQt6Xml.so.6
  sudo cp -v $QTDIRLIB/libQt6Multimedia.so.6 ./package/usr/lib/lmc/libQt6Multimedia.so.6
  sudo cp -v -r ../../release/imageformats ./package/usr/lib/lmc
  sudo cp -v -r ../../release/platforms ./package/usr/lib/lmc
  # Qt 6 TLS backends may be absent in Qt builds without SSL.
  if [ -d ../../release/tls ]; then
    sudo cp -v -r ../../release/tls ./package/usr/lib/lmc
  fi
fi
sudo cp -v ../../release/liblmcapp.so.2 ./package/usr/lib/lmc/liblmcapp.so.2
sudo cp -v ../../release/lmc.rcc ./package/usr/lib/lmc/lmc.rcc
sudo cp -v ../../release/lan-messenger ./package/usr/lib/lmc/lan-messenger
sudo cp -v ../../release/COPYING ./package/usr/lib/lmc/COPYING
sudo cp -v -r ../../release/lang ./package/usr/lib/lmc
sudo cp -v -r ../../release/sounds ./package/usr/lib/lmc
sudo cp -v -r ../../release/themes ./package/usr/lib/lmc

echo "BUILDING PACKAGE..."
DEB_BUILD_ARCH=$(dpkg-architecture -qDEB_BUILD_ARCH)
sudo sed -i -e "s/VERSION/$1/g" ./package/DEBIAN/control
sudo sed -i -e "s/ARCH/$DEB_BUILD_ARCH/g" ./package/DEBIAN/control
sudo chmod 755 ./package/DEBIAN/postinst
sudo chmod 755 ./package/DEBIAN/postrm
sudo chmod 755 ./package/DEBIAN/prerm
sudo chmod 755 ./package/usr/lib/lmc/lmc.sh
sudo chmod 755 ./package/usr/lib/lmc/whitelist
sudo dpkg-deb -z9 -Zxz -b package ../lmc_$1_$(arch)$PACKAGE_MODE.deb

echo "DONE."
exit 0