#!/bin/sh

if [ "$1" = "" ]; then
  echo "Usage: setup <App Version>"
  echo "eg: setup 1.0.0"
  exit 1
fi

QTDIR=/home/dilip/QtSDK/Desktop/Qt/4.8.0/gcc

sudo echo "COPYING FILES..."
sudo cp -v $QTDIR/lib/libQtCore.so.4 ./package/usr/lib/lmc/libQtCore.so.4
sudo cp -v $QTDIR/lib/libQtGui.so.4 ./package/usr/lib/lmc/libQtGui.so.4
sudo cp -v $QTDIR/lib/libQtNetwork.so.4 ./package/usr/lib/lmc/libQtNetwork.so.4
sudo cp -v $QTDIR/lib/libQtXml.so.4 ./package/usr/lib/lmc/libQtXml.so.4
sudo cp -v $QTDIR/lib/libQtWebKit.so.4 ./package/usr/lib/lmc/libQtWebKit.so.4
sudo cp -v ../../release/libcrypto.so.1.0.0 ./package/usr/lib/lmc/libcrypto.so.1.0.0
sudo cp -v ../../release/liblmcapp.so.2 ./package/usr/lib/lmc/liblmcapp.so.2
sudo cp -v ../../release/lmc.rcc ./package/usr/lib/lmc/lmc.rcc
sudo cp -v ../../release/lan-messenger ./package/usr/lib/lmc/lan-messenger
sudo cp -v ../../release/COPYING ./package/usr/lib/lmc/COPYING
sudo cp -v -r ../../release/lang ./package/usr/lib/lmc
sudo cp -v -r ../../release/sounds ./package/usr/lib/lmc
sudo cp -v -r ../../release/themes ./package/usr/lib/lmc
sudo cp -v -r ../../release/imageformats ./package/usr/lib/lmc

echo "BUILDING PACKAGE..."
sudo dpkg-deb -z9 -Zlzma -b package ../lmc_$1_i386.deb

echo "DONE."
exit 0